/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.io.File;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author AAX
 */
public class UppdateraAnstalldaProj extends javax.swing.JFrame {
    
    private InfDB databas;
    private int sid;
    public Validation validation = new Validation(); 
    
    public void setText(int sid) {
       this.sid = sid;
       String sql = "select anstalld.aid, anstalld.namn from anstalld join ARBETAR_I on ANSTALLD.AID=ARBETAR_I.AID where ARBETAR_I.SID = "+sid;
        String output = "";
        
        try {
            ArrayList<HashMap<String, String>> spelprojekt = databas.fetchRows(sql);
            if(spelprojekt != null) {
                for (int i = 0; i < spelprojekt.size(); i++) {
                    output+= spelprojekt.get(i).get("AID") + spelprojekt.get(i).get("NAMN") + "\n";
                }
            }
            else {
                output = "det finns inga anställda för valt spelprojekt.";
            }
            }catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
        anstalldaField.setText("AID, NAMN\n" + output);
    }
    
    public void allaAnstallda() {
       String sql = "select anstalld.aid, anstalld.namn from anstalld";
        String output = "";
        
        try {
            ArrayList<HashMap<String, String>> spelprojekt = databas.fetchRows(sql);
            if(spelprojekt != null) {
                for (int i = 0; i < spelprojekt.size(); i++) {
                    output+= spelprojekt.get(i).get("AID") + spelprojekt.get(i).get("NAMN") + "\n";
                }
            }
            else {
                output = "det finns inga anställda för valt spelprojekt.";
            }
            }catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
        allaAnstallda.setText("AID, NAMN\n" + output);
        
    }
    
    public void addAnstalld(int aid, int sid) {
        String sql = "insert into ARBETAR_I (AID,SID) values ("+aid+","+sid+")";
        try {
        databas.insert(sql);
        
        }catch (NumberFormatException e) {  
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Något gick fel med inmatningen");
            }
            catch (InfException e) {  
                System.out.println(e.getMessage());
                if(e.getErrorCode() == 0) {
                    JOptionPane.showMessageDialog(null, "Du måste först registrera valt AID som specialist före du kan lägga till dem till ett projekt!");
                }
                else
                JOptionPane.showMessageDialog(null, "Något gick fel vid kontakten med databasen");
                
            }
    }
    
    public void removeAnstalld(int aid, int sid) {
        String sql = "DELETE FROM arbetar_i WHERE AID="+aid+" and sid="+sid;
        try {
        databas.delete(sql);
        
        }catch (NumberFormatException e) {  
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Något gick fel med inmatningen");
            }
            catch (InfException e) {  
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Något gick fel vid kontakten med databasen");
                
            }
        
        
    }
    /**
     * Creates new form UppdateraAnstalldaProj
     */
    public UppdateraAnstalldaProj() {
        initComponents();
        
        try {
            String path = Paths.get("").toAbsolutePath().toString() + File.separator + "MICEDB.FDB";
            databas = new InfDB(path);
            
            }
        catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
        allaAnstallda();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        anstalldaField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        removeField = new javax.swing.JTextField();
        addField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addbutton = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        allaAnstallda = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        anstalldaField.setColumns(20);
        anstalldaField.setRows(5);
        jScrollPane1.setViewportView(anstalldaField);

        jLabel1.setText("Ta bort anstalld frårn projekt");

        jLabel2.setText("Lägg till anställd till projekt");

        removeField.setText("AID");

        addField.setText("AID");

        jLabel3.setText("Anställda för projekt");

        addbutton.setText("Lägg till!");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        remove.setText("Ta bort!");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        allaAnstallda.setColumns(20);
        allaAnstallda.setRows(5);
        jScrollPane2.setViewportView(allaAnstallda);

        jLabel4.setText("Alla Anställda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addbutton)
                        .addComponent(jLabel2)
                        .addComponent(remove)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane1)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(removeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(remove)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(addField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addbutton)))
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        int selectaid = Integer.parseInt(removeField.getText());
        removeAnstalld(selectaid, sid);
        setText(sid);
    }//GEN-LAST:event_removeActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        int selectaid = Integer.parseInt(addField.getText());
        addAnstalld(selectaid, sid);
        setText(sid);
    }//GEN-LAST:event_addbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UppdateraAnstalldaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UppdateraAnstalldaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UppdateraAnstalldaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UppdateraAnstalldaProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UppdateraAnstalldaProj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addField;
    private javax.swing.JButton addbutton;
    private javax.swing.JTextArea allaAnstallda;
    private javax.swing.JTextArea anstalldaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton remove;
    private javax.swing.JTextField removeField;
    // End of variables declaration//GEN-END:variables
}
