/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;

import java.io.File;
import java.nio.file.Paths;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author AAX
 */
public class uppdateraSpecialistroll extends javax.swing.JFrame {
    private InfDB databas;
    private int aid;
    boolean orgleader=false;
    boolean orgspecial=false;
    /**
     * Creates new form uppdateraSpecialistroll
     */
    public uppdateraSpecialistroll() {
        initComponents();
        try {
            String path = Paths.get("").toAbsolutePath().toString() + File.separator + "MICEDB.FDB";
            databas = new InfDB(path);
            
            }
        catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public void getValues(int aid) {
        this.aid = aid;
        String sql ="select projektledare.aid from projektledare join anstalld on projektledare.aid=anstalld.aid where anstalld.aid="+aid;
        String sql2 ="select specialist.aid from specialist join anstalld on specialist.aid=anstalld.aid where anstalld.aid="+aid;
        
        
        try {
            String leader = databas.fetchSingle(sql);
            String special = databas.fetchSingle(sql2);
            if(leader!=null){
            projradio.setSelected(true);
            this.orgleader=true;
            }
            
            if(special!=null){
            specRadio.setSelected(true);
            this.orgspecial=true;
            }
        }
        
        catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public String getName(int aid) {
        String sql ="SELECT NAMN from anstalld where anstalld.aid="+aid;
        String name="";
        try {
        name = databas.fetchSingle(sql);
        }catch (InfException ex) {
            System.out.println(ex.getMessage());
        }
        return name;
    }
    
    public void setLabel(String name) {
        speciallabel.setText("Sätt kompetens för "+name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speciallabel = new javax.swing.JLabel();
        projradio = new javax.swing.JRadioButton();
        specRadio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        speciallabel.setText("Uppdatera namns specialistroll");

        projradio.setText("Projektledare");
        projradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projradioActionPerformed(evt);
            }
        });

        specRadio.setText("Specialist");

        jButton1.setText("Spara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(speciallabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(specRadio)
                            .addComponent(projradio)
                            .addComponent(jButton1))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(speciallabel)
                .addGap(31, 31, 31)
                .addComponent(projradio)
                .addGap(18, 18, 18)
                .addComponent(specRadio)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projradioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String projsql = "";
        String specsql = "";
        
        if(orgleader != projradio.isSelected()) {
            try {
                if(projradio.isSelected()){
                    projsql = "insert into PROJEKTLEDARE (aid) values ("+aid+")";
                    databas.insert(projsql);
                    }
                else if(!projradio.isSelected()){
                    projsql ="delete from PROJEKTLEDARE WHERE AID="+aid;
                    databas.delete(projsql);
                }
                    JOptionPane.showMessageDialog(null, getName(aid)+"s projektledarroll har blivit uppdaterad!");
                } 
                catch (InfException e) {  
                    System.out.println(e.getMessage());
                    if(e.getErrorCode()==0) 
                        JOptionPane.showMessageDialog(null, "Den anställde är satt som projektledare för minst ett projekt, byt projektledare för projekt innan dess projektledarroll kan tas bort.");
                    else
                    JOptionPane.showMessageDialog(null, "Något gick fel vid kontakten med databasen");

                }
            }
        if(orgspecial != specRadio.isSelected()) {
            try {
                if(specRadio.isSelected()){
                    specsql = "insert into SPECIALIST (aid) values ("+aid+")";
                    databas.insert(specsql);}
                else if(!specRadio.isSelected()){
                    specsql ="delete from SPECIALIST WHERE AID="+aid;  
                    databas.delete(specsql);
                }
                    JOptionPane.showMessageDialog(null, getName(aid)+"s specialistroll har blivit uppdaterad!");
                } 
                catch (InfException e) {  
                    System.out.println(e.getMessage());
                    JOptionPane.showMessageDialog(null, "Något gick fel vid kontakten med databasen");

                }
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uppdateraSpecialistroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uppdateraSpecialistroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uppdateraSpecialistroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uppdateraSpecialistroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uppdateraSpecialistroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton projradio;
    private javax.swing.JRadioButton specRadio;
    private javax.swing.JLabel speciallabel;
    // End of variables declaration//GEN-END:variables
}
